// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/401': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/401').default>>>>
    }
    '/403': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/403').default>>>>
    }
    '/500': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/500').default>>>>
    }
    '/': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/index').default>>>>
    }
    '/list/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/list/[id].delete').default>>>>
    }
    '/list/basic-list': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/list/basic-list.post').default>>>>
    }
    '/list/consult-list': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/list/consult-list.post').default>>>>
    }
    '/list/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/list/create.post').default>>>>
    }
    '/list/crud-table': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/list/crud-table.post').default>>>>
    }
    '/list': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/list/index.post').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/list/index.put').default>>>>
    }
    '/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/login.post').default>>>>
    }
    '/logout': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/logout').default>>>>
    }
    '/menu': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/menu/index').default>>>>
    }
    '/test': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/test.delete').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/test.post').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/test.put').default>>>>
    }
    '/user/info': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/user/info').default>>>>
    }
  }
}
export {}